# Generated by Django 4.2.3 on 2023-07-28 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=50)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=500)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('ratings', models.JSONField()),
                ('metascore', models.IntegerField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('imdb_votes', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=50)),
                ('dvd', models.DateField(blank=True, null=True)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('production', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('response', models.BooleanField(default=False)),
            ],
        ),
    ]
