# Generated by Django 3.2.13 on 2023-07-29 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=50)),
                ('released', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=500)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
                ('ratings', models.JSONField()),
                ('metascore', models.CharField(blank=True, max_length=3, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=3, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('imdb_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('dvd', models.CharField(blank=True, max_length=20, null=True)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('production', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
