# Generated by Django 3.2.13 on 2023-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
